### ISSUE TITLE
一个比较奇葩的点子可以做到同样的效果

### ISSUE THREAD

**Issue by dawn-lc** [SlimeNull/Null.TextEditor#2]
记录控制台光标的位置到变量，然后输出需要输出的文字，计算光标位置的差，不就得到文字的显示宽度了吗。

**Comment by SlimeNull** [comment]
嗯, 是的, 雀食这样弄了, 但是我要实现的是, 不进行输出直接进行测量, 不过我上次通过这种方式获取所有字符宽度后直接把结果存储起来然后生成对应的判断语句了, 见: nuget:NullLib.ConsoleEx
